import os
from pathlib import Path
from nmh_gcl import NmhGcl
from glob import glob

TOOL_NAME = "Jyl's NMH GCL exporter"

DIR = "filesystem/DATA/files/STG_HI"
OUT_DIR = "out/STG_HI"


def convert(in_path: str, out_dir: str):
    print(in_path)
    gcl: NmhGcl = NmhGcl.from_file(in_path)

    out_path = os.path.join(out_dir, Path(in_path).stem + ".obj")

    with open(out_path, "w") as f:
        f.write("# OBJ file\n")
        f.write(f"# Generated by {TOOL_NAME}\n")

        last_index = 0

        for i in range(gcl.num_areas):
            area_header = gcl.area_headers[i]
            f.write(f"o {area_header.name}_{i}\n")

            area = gcl.areas[i]

            for tri in area.unknown2s:
                f.write(f"v {tri.v0.x} {tri.v0.y} {tri.v0.z}\n")
                f.write(f"v {tri.v1.x} {tri.v1.y} {tri.v1.z}\n")
                f.write(f"v {tri.v2.x} {tri.v2.y} {tri.v2.z}\n")

            for ii in range(last_index, last_index + area.num_unknown2s):
                f.write(f"f {ii * 3 + 1} {ii * 3 + 2} {ii * 3 + 3}\n")

            last_index += area.num_unknown2s


def convert_all(dir: str, out_dir: str):
    # out dir exists
    os.makedirs(out_dir, exist_ok=True)

    # rm old files
    files = glob(os.path.join(out_dir, "*"))
    for f in files:
        os.remove(f)

    # convert all
    for file in os.listdir(dir):
        if file.endswith(".GCL"):
            path = os.path.join(dir, file)
            convert(path, out_dir)


if __name__ == "__main__":
    convert_all(DIR, OUT_DIR)
